apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  selector:
    app: flaskapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 9000
      nodePort: 31100